name: Tuist pipeline

on: [ push, pull_request ]

jobs:
  build:
    name: Build the app
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Tuist
        run: curl -Ls https://install.tuist.io | bash

      - name: Fetch dependencies
        run: tuist fetch

      - name: Build
        run: tuist build

      - name: SwiftLint
        run: swiftlint Sources/ Tests/ UITests/

      - name: Run tests
        run: tuist test
