name: Tuist pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  tests:
    name: Run tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Tuist
        run: curl -Ls https://install.tuist.io | bash

      - name: Fetch dependencies
        run: tuist fetch

      - name: Run tests
        run: tuist test --clean
